# DATA ANALYSIS
Merge the datasets

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving rss_skills_dataset_grouped (1).csv to rss_skills_dataset_grouped (1).csv
Saving rss_skills_dataset_grouped.csv to rss_skills_dataset_grouped.csv
Saving skills_dataset_grouped (3).csv to skills_dataset_grouped (3).csv
Saving skills_dataset_grouped (2).csv to skills_dataset_grouped (2).csv
Saving skills_dataset_grouped (1).csv to skills_dataset_grouped (1).csv
Saving skills_dataset_grouped.csv to skills_dataset_grouped.csv

In [ ]:
import pandas as pd
import glob

csv_files = glob.glob("*.csv")

dfs = [pd.read_csv(f) for f in csv_files]
df = pd.concat(dfs, ignore_index=True)

df.shape   # check rows & columns
df.head()  # preview

,topic,title,tokens,ner_tags,extracted_skills,num_tokens,num_skills_found
0,tech_news,"Nordic founders are taking bigger swings, and ...","[""Nordic"", ""founders"", ""are"", ""taking"", ""bigge...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""Apple Podcasts"", ""Overcast"", ""Spotify""...",181,5
1,tech_news,Here are the 49 US AI startups that have raise...,"[""Here"", ""are"", ""the"", ""49"", ""US"", ""AI"", ""star...","[""O"", ""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"",...","[""AI"", ""AI agents"", ""AI applications"", ""AI cha...",3197,152
2,tech_news,JustiGuide wants to use AI to help people navi...,"[""JustiGuide"", ""wants"", ""to"", ""use"", ""AI"", ""to...","[""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"", ""O"",...","[""AI"", ""Google Cloud"", ""Hugging Face"", ""Facebo...",737,14
3,tech_news,OpenAI claims teen circumvented safety feature...,"[""OpenAI"", ""claims"", ""teen"", ""circumvented"", ""...","[""B-SKILL"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"",...","[""OpenAI"", ""ChatGPT"", ""Google Cloud"", ""Netflix...",860,43
4,tech_news,Redwood Materials reportedly cuts 5% of staff ...,"[""Redwood"", ""Materials"", ""reportedly"", ""cuts"",...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""data centers""]",209,2

Check the columns

In [ ]:
df.columns

Index(['topic', 'title', 'tokens', 'ner_tags', 'extracted_skills',
       'num_tokens', 'num_skills_found'],
      dtype='object')

Check null values

In [ ]:
df.isna().sum()

topic               0
title               0
tokens              0
ner_tags            0
extracted_skills    0
num_tokens          0
num_skills_found    0
dtype: int64

In [ ]:
df.shape

(740, 7)

In [ ]:
# Convert columns to int
df['num_tokens'] = df['num_tokens'].astype(int)
df['num_skills_found'] = df['num_skills_found'].astype(int)

In [ ]:
# Keep only rows where both columns are integers
df = df[df['num_tokens'].apply(lambda x: str(x).isdigit()) &
        df['num_skills_found'].apply(lambda x: str(x).isdigit())]

In [ ]:
df.shape

(740, 7)

In [ ]:
df = df[df.notna().sum(axis=1) <= 7]

In [ ]:
df.shape

(740, 7)

In [ ]:
df['topic'].unique()

array(['tech_news', 'dev_news', 'security', 'ai_ml', 'cloud',
       'devops_programming', 'security_heavy', 'ai_research',
       'data visualization', 'business intelligence',
       'predictive analytics', 'reinforcement learning', 'cybersecurity',
       'AI', 'machine learning', 'cloud computing', 'programming',
       'web development', 'data engineering', 'artificial intelligence',
       'deep learning', 'natural language processing', 'computer vision',
       'microservices', 'backend development', 'full stack development',
       'big data', 'data science', 'IoT', 'blockchain', 'DevOps',
       'robotics', 'quantum computing', 'augmented reality',
       'virtual reality', 'edge computing', 'cyber threat intelligence',
       'kubernetes', 'network security', 'fintech'], dtype=object)

In [ ]:
df['topic'].value_counts()

topic
tech_news                      130
ai_research                     68
dev_news                        63
security                        58
devops_programming              35
cloud                           29
ai_ml                           21
security_heavy                  20
cloud computing                 20
cybersecurity                   20
data engineering                19
machine learning                18
AI                              18
business intelligence           10
programming                     10
artificial intelligence         10
computer vision                 10
augmented reality               10
edge computing                  10
cyber threat intelligence       10
IoT                             10
blockchain                      10
DevOps                          10
robotics                        10
kubernetes                      10
quantum computing               10
fintech                          9
virtual reality                  9
deep learning                    9
data science                     9
network security                 8
data visualization               8
predictive analytics             7
big data                         7
natural language processing      6
microservices                    6
full stack development           6
web development                  4
reinforcement learning           2
backend development              1
Name: count, dtype: int64

In [ ]:
df.shape

(740, 7)

Save the merged dataset

In [ ]:

df.to_csv('clean_topics.csv', index=False, encoding='utf-8', quoting=1)

Upload the merged dataset

In [ ]:
from google.colab import files
import pandas as pd

# Suppose the file is "news_dataset.csv"
df = pd.read_csv("/content/clean_topics.csv")
df.head()

,topic,title,tokens,ner_tags,extracted_skills,num_tokens,num_skills_found
0,tech_news,"Nordic founders are taking bigger swings, and ...","[""Nordic"", ""founders"", ""are"", ""taking"", ""bigge...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""Apple Podcasts"", ""Overcast"", ""Spotify""...",181,5
1,tech_news,Here are the 49 US AI startups that have raise...,"[""Here"", ""are"", ""the"", ""49"", ""US"", ""AI"", ""star...","[""O"", ""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"",...","[""AI"", ""AI agents"", ""AI applications"", ""AI cha...",3197,152
2,tech_news,JustiGuide wants to use AI to help people navi...,"[""JustiGuide"", ""wants"", ""to"", ""use"", ""AI"", ""to...","[""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"", ""O"",...","[""AI"", ""Google Cloud"", ""Hugging Face"", ""Facebo...",737,14
3,tech_news,OpenAI claims teen circumvented safety feature...,"[""OpenAI"", ""claims"", ""teen"", ""circumvented"", ""...","[""B-SKILL"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"",...","[""OpenAI"", ""ChatGPT"", ""Google Cloud"", ""Netflix...",860,43
4,tech_news,Redwood Materials reportedly cuts 5% of staff ...,"[""Redwood"", ""Materials"", ""reportedly"", ""cuts"",...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""data centers""]",209,2

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)  # remove punctuation
    text = text.strip()
    return text

# Clean topic and title
df['topic_clean'] = df['topic'].apply(clean_text)
df['title_clean'] = df['title'].apply(clean_text)

In [ ]:
df.shape

(740, 9)

In [ ]:
df.head()

,topic,title,tokens,ner_tags,extracted_skills,num_tokens,num_skills_found,topic_clean,title_clean
0,tech_news,"Nordic founders are taking bigger swings, and ...","[""Nordic"", ""founders"", ""are"", ""taking"", ""bigge...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""Apple Podcasts"", ""Overcast"", ""Spotify""...",181,5,tech_news,nordic founders are taking bigger swings and i...
1,tech_news,Here are the 49 US AI startups that have raise...,"[""Here"", ""are"", ""the"", ""49"", ""US"", ""AI"", ""star...","[""O"", ""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"",...","[""AI"", ""AI agents"", ""AI applications"", ""AI cha...",3197,152,tech_news,here are the 49 us ai startups that have raise...
2,tech_news,JustiGuide wants to use AI to help people navi...,"[""JustiGuide"", ""wants"", ""to"", ""use"", ""AI"", ""to...","[""O"", ""O"", ""O"", ""O"", ""B-SKILL"", ""O"", ""O"", ""O"",...","[""AI"", ""Google Cloud"", ""Hugging Face"", ""Facebo...",737,14,tech_news,justiguide wants to use ai to help people navi...
3,tech_news,OpenAI claims teen circumvented safety feature...,"[""OpenAI"", ""claims"", ""teen"", ""circumvented"", ""...","[""B-SKILL"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"",...","[""OpenAI"", ""ChatGPT"", ""Google Cloud"", ""Netflix...",860,43,tech_news,openai claims teen circumvented safety feature...
4,tech_news,Redwood Materials reportedly cuts 5% of staff ...,"[""Redwood"", ""Materials"", ""reportedly"", ""cuts"",...","[""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ""O"", ...","[""AI"", ""data centers""]",209,2,tech_news,redwood materials reportedly cuts 5 of staff a...

In [ ]:
df.columns

Index(['topic', 'title', 'tokens', 'ner_tags', 'extracted_skills',
       'num_tokens', 'num_skills_found', 'topic_clean', 'title_clean'],
      dtype='object')

Remove duplicates

In [ ]:
df = df.drop_duplicates(subset=['topic_clean', 'title_clean','tokens'])

In [ ]:
df.shape

(692, 9)

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

In [ ]:
from os import read
df=pd.read_csv("/content/cleaned_dataset.csv")

Pending : Extracting only valid skills from the dataset

In [ ]:
# from collections import Counter
# import pandas as pd

# skill_counter = Counter()

# for row in df['skills']:
#     if isinstance(row, str):
#         for s in row.split(","):
#             skill_counter[s.strip()] += 1

# # Convert the Counter object to a Pandas DataFrame and save it to CSV
# skill_df = pd.DataFrame(skill_counter.items(), columns=['skill', 'count'])
# skill_df.to_csv("skill_counter.csv", index=False)

unique skills

In [ ]:
# import pandas as pd

# unique_skills = set()

# for row in df["skills"]:
#     if isinstance(row, str):
#         for s in row.split(","):
#             unique_skills.add(s.strip())

# # Convert the set to a Pandas DataFrame before saving to CSV
# unique_skills_df = pd.DataFrame(list(unique_skills), columns=['skill'])
# unique_skills_df.to_csv("unique_skills.csv", index=False)

In [ ]:
# import matplotlib.pyplot as plt

# # Sort skill_df by count and plot the top 15
# skill_df.sort_values(by='count', ascending=False).head(15).plot(x='skill', y='count', kind='bar', figsize=(12,6))
# plt.title("Top 15 Most Frequent Skills")
# plt.xlabel("Skill")
# plt.ylabel("Frequency")
# plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
# plt.tight_layout() # Adjust layout to prevent labels from overlapping
# plt.show()

In [ ]:
df.to_csv("merged_cleaned_dataset.csv", index=False)

In [ ]:
df.shape

In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/merged_cleaned_dataset.csv")

def extract(col):
    out = []
    for v in df[col].dropna():
        for s in str(v).split(","):
            s = s.strip()
            if s:
                out.append(s)
    return out

skills = sorted(set(extract("skills") + extract("skills_list")))
pd.DataFrame({"skill": skills}).to_csv("unique_skills.csv", index=False)

In [ ]:
from google.colab import files
import pandas as pd

# Upload file
# uploaded = files.upload()

# Suppose the file is "news_dataset.csv"
df = pd.read_csv("/content/sample_data/unique_skills (1).csv")
df.head()

In [ ]:
df['skill_lower'] = df['skill'].str.lower()

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
num_duplicates = df['skill_lower'].duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

In [ ]:
skills = df['skill_lower']
clean_skills = list(set(skills))
print("Number of unique skills after removing duplicates:", len(clean_skills))

In [ ]:
import pandas as pd

clean_skills_df = pd.DataFrame(clean_skills, columns=['skill'])
clean_skills_df.to_csv("clean_skills.csv", index=False)

In [ ]:
from google.colab import files
import pandas as pd

# Upload file
# uploaded = files.upload()

# Suppose the file is "news_dataset.csv"
df = pd.read_csv("/content/clean_skills.csv")
df.head()

In [ ]:
# Assuming the column with Yes/No is named 'Valid'
valid_skills = df[df['valid'].str.strip().str.lower() == 'yes']

In [ ]:
valid_skills.shape

In [ ]:
valid_skills.to_csv("valid_skills.csv", index=False)

Preprocess the Titles

In [ ]:
from google.colab import files
import pandas as pd

# Upload file
# uploaded = files.upload()

# Suppose the file is "news_dataset.csv"
df = pd.read_csv("/content/sample_data/merged_cleaned_dataset (1).csv")
df.head()

In [ ]:
import pandas as pd
import re

df['title'] = df['title'].str.lower().apply(lambda x: re.sub(r'[^a-z0-9\s]', '', x))

In [ ]:
df.to_csv("cleaned_titles.csv", index=False)

Prepare the Skill Labels

In [ ]:
import pandas as pd

# Load your cleaned unique skills CSV
valid_skills_df = pd.read_csv("valid_skills.csv")  # adjust filename